title: "Qingcheng\'s Site"
paginate: 5
title: "Qingcheng\'s Site"
theme: 'hugo-PaperMod'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Qingcheng\'s Site"
  description: "Personal blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: "Qingcheng Zhao"
  # author: ["Me", "You"] # multiple authors
  DateFormat: "Mon, Jan 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"
    icon: favicon.ico
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Qingcheng Zhao's Homepage"
    subtitle: "Hello \U0001F44B, I am Qingcheng, an undergraduate student."
    imageUrl: "me.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: About
        url: about
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to Qingcheng Zhao's blog

  socialIcons:
    - name: email
      url: "mailto: zhaoqch1@shanghaitech.edu.cn"
    - name: telegram
      url: "https://t.me/clarive0"
    - name: github
      url: "https://github.com/Clarivy/"
    - name: QQ
      url: "https://qm.qq.com/cgi-bin/qm/qr?k=LlWK_mAFaLGthi85kjsXcBkfKo47H-qd&noverify=0"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    linkFullImages: true

  editPost:
    URL: "https://github.com/Clarivy/hugo-homepage"
    Text: "Suggest Changes" # edit text
    appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: search
      name: search
      url: search
      weight: 20
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: github
      name: my github
      url: https://github.com/Clarivy/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai